model_arch: DR-reformer
encoder_learned_pos: true
decoder_learned_pos: true
data_path: /home/a/wmt17/pre-train
model_dir: /home/a/wmt17/model/pre-model
update_freq: 32
log_interval: 100
save_interval_updates: 5000
max_tokens: 512
max_source_positions: 512
max_target_positions: 512
lr: 0.001
dropout: 0.3
criterion: label_smoothed_cross_entropy
reset_optimizer: true
reset_lr_scheduler: true
reset_dataloader: true
reset_meters: true
lr_scheduler: inverse_sqrt
weight_decay: 0.0
clip_norm: 0.0
warmup_init_lr: 1e-07
label_smoothing: 0.1
fp16: true
seed: 1
